DROP TABLE IF EXISTS NEWS;

CREATE TABLE NEWS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  PLAYERNAME VARCHAR(250) NOT NULL,
  SOURCE VARCHAR(250) NOT NULL,
  COMMENTS VARCHAR(250) DEFAULT NULL,
  TIMESTAMP TIMESTAMP NOT NULL
);